name: VeriFlow Mobile | Compile Project

permissions:
  contents: write
  pull-requests: write
  issues: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

run-name: '👷🚧[#${{ github.run_number }}][VeriFlow Compile | Mobile] PR: "${{ github.event.pull_request.title }}"'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'VeriFlow_Mobile/**'
  push:
    branches:
      - main
    paths:
      - 'VeriFlow_Mobile/**'
  workflow_dispatch:

jobs:
  filter:
    name: "Filter changes"
    runs-on: ubuntu-latest
    outputs:
      only_mobile: ${{ steps.filter.outputs.only_mobile }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Detect folder changes"
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            only_mobile:
              - 'VeriFlow_Mobile/**'
            others:
              - 'VeriFlow/**'
              - 'VeriFlow_Web/**'
              - 'VeriFlow_Common/**'
              - 'VeriFlow_DB/**'
              - 'VeriFlow_API/**'

  build:
    needs: filter
    if: needs.filter.outputs.only_mobile == 'true'
    runs-on: ubuntu-latest
    name: "Compile Project 📱"
    defaults:
      run:
        working-directory: VeriFlow_Mobile

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4

      - name: "Set up Java"
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: "Cache Gradle packages"
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('VeriFlow_Mobile/**/*.gradle*', 'VeriFlow_Mobile/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Grant execute permission for gradlew"
        run: chmod +x ./gradlew

      - name: "Run Gradle build without tests"
        id: gradle_build
        run: ./gradlew compileTestJava
        continue-on-error: true

      - name: "Set build result"
        if: always()
        run: |
          if [[ "${{ steps.gradle_build.outcome }}" == "failure" ]]; then
            echo "result=failure" >> $GITHUB_ENV
            exit 1
          else
            echo "result=success" >> $GITHUB_ENV
          fi

      - name: "Apply Labels"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && always()
        uses: actions/github-script@v7
        env:
          result: ${{ env.result }}
        with:
          script: |
            const labels = [
              { name: 'build-success', color: '0E8A16', description: 'Build and tests succeeded' },
              { name: 'build-failure', color: 'B60205', description: 'Build or tests failed' }
            ];

            const resultLabel = process.env.result === 'success' ? 'build-success' : 'build-failure';
            const removeLabel = resultLabel === 'build-success' ? 'build-failure' : 'build-success';

            const issue_number = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            for (const label of labels) {
              try {
                await github.rest.issues.updateLabel({
                  owner,
                  repo,
                  name: label.name,
                  color: label.color,
                  description: label.description
                });
              } catch (error) {
                if (error.status === 404) {
                  await github.rest.issues.createLabel({
                    owner,
                    repo,
                    name: label.name,
                    color: label.color,
                    description: label.description
                  });
                }
              }
            }

            try {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number,
                name: removeLabel
              });
            } catch (error) {
              if (error.status !== 404) throw error;
            }

            await github.rest.issues.addLabels({
              owner,
              repo,
              issue_number,
              labels: [resultLabel]
            });

      - name: "Post Comment on PR"
        if: github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const url = `${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const resultMessage = process.env.result === 'success'
              ? `✅ Build completed successfully.\n\n[View Workflow Run](${url})`
              : `❌ Build failed, check the logs for more details.\n\n[View Workflow Run](${url})`;

            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: resultMessage
            });
