name: VeriFlow | Validate PR

run-name: "👷🚧[#${{ github.run_number }}][Validate PR] PR: \"${{ github.event.pull_request.title }}\""

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

permissions:
  pull-requests: write
  contents: read
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Validate PR🔖"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_GITHUB_KEY }}

      - name: "Auto Assign PR"
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.PERSONAL_GITHUB_KEY }}

      - name: "Get PR Author"
        id: pr_author
        run: echo "author=$(jq --raw-output .pull_request.user.login $GITHUB_EVENT_PATH)" >> "$GITHUB_OUTPUT"

      - name: "Assign label based on author"
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_GITHUB_KEY }}
          script: |
            const author = '${{ steps.pr_author.outputs.author }}';
            let label = '';

            const chappy = ['ta543'];
            const zakke = ['x'];

            if (chappy.includes(author)) {
              label = 'chappy';
            }

            if (zakke.includes(author)) {
              label = 'zakke';
            }

            if (label) {
              const issue_number = context.issue.number;
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number,
                labels: [label],
              });
            }
